export const mockItinerary =[{
  itinerary_id: 7,
  start_address: "Denver, CO 80202, USA",
  end_address: "366 Broadway, Denver, CO 80203, USA",
  favorite: false,
  departure_time: "3:51pm",
  arrival_time: "4:11pm",
  duration: "20 mins",
  distance: "3.0 mi",
  steps: [{
    id: 26,
    possible_route_id: 7,
    headsign: null,
    arrival_time: null,
    departure_time: null,
    arrival_stop: null,
    departure_stop: null,
    name: null,
    short_name: null,
    instructions: "Walk to Union Sta,tion",
    distance: "1 ft",
    duration: "1 min",
    color: null,
    num_stops: null,
    vehicle_type: null,
    credit_name: null,
    credit_url: null,
    travel_mode: "Walking"
  },
  {
    id: 27,
    possible_route_id: 7,
    headsign: "Highlands Ranch",
    arrival_time: "4:11pm",
    departure_time: "3:52pm",
    arrival_stop: "Broadway & 4th Ave",
    departure_stop: "Union Station",
    name: "South Broadway",
    short_name: "0",
    instructions: "Bus towards Highlands Ranch",
    distance: "3.0 mi",
    duration: "20 mins",
    color: "#0277bd",
    num_stops: 11,
    vehicle_type: "Bus",
    credit_name: "Regional Transportation District",
    credit_url: "http://rtd-denver.com/",
    travel_mode: "TRANSIT"
},
{
    id: 28,
    possible_route_id: 7,
    headsign: null,
    arrival_time: null,
    departure_time: null,
    arrival_stop: null,
    departure_stop: null,
    name: null,
    short_name: null,
    instructions: "Walk to 366 Broadway, Denver, CO 80203, USA",
    distance: "108 ft",
    duration: "1 min",
    color: null,
    num_stops: null,
    vehicle_type: null,
    credit_name: null,
    credit_url: null,
    travel_mode: "Walking"
  }]

}]